apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: go-notify-secrets
  namespace: go-notify
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: go-notify-secrets
    creationPolicy: Owner
  data:
  - secretKey: SCHWAB_API_KEY
    remoteRef:
      key: secret/data/go-notify
      property: SCHWAB_API_KEY
  - secretKey: SCHWAB_API_SECRET
    remoteRef:
      key: secret/data/go-notify
      property: SCHWAB_API_SECRET
