apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        # User must configure one of the following:
        # 1. Kubernetes Auth (Recommended)
        kubernetes:
          mountPath: "kubernetes"
          role: "go-notify-role" # Needs to be created in Vault
          serviceAccountRef:
            name: "default"
            namespace: "go-notify"
        # 2. Token Auth (Simple/Insecure)
        # tokenSecretRef:
        #   name: "vault-token"
        #   namespace: "external-secrets"
        #   key: "token"
